### ISSUE TITLE
Whats the use case for this?

### ISSUE THREAD

**Issue by frank-dspeed** [WebReflection/path-crawler#1]
Hello i am wondering what the exact usecase is?

For me it looks like you plan to traverse a DOM tree with that?

**Comment by WebReflection** [comment]
it's about serialization and de-serialization of objects, or manipulation before/after post messages dance, as example by posting Maps or Sets as entries and have these back once retrieved on the other side.

This utility has nothing to do with the DOM, but I haven't had a chance to talk about it, or showcase properly how to use it.

Reason I haven't even twitted, or mentioned, this.

Not sure why it has 4 stars already 😅

Hope this answers.
